trigger:
- main

pool:
  name: fasil-pool
  demands:
    - Agent.Name -equals shanu

steps:
- task: Maven@4
  inputs:
    azureSubscription: 'Free Trial (7f5ef2b9-b991-442f-80cb-51fc34b43bad)'
    mavenPomFile: 'pom.xml'
    options: '-DskipTests'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'