trigger:
- main

pool:
  name: fasil-pool
  demands:
    - Agent.Name -equals shanu

steps:
- task: Maven@3
  displayName: 'Maven Build (Java 17)'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'               # Use path instead of JDKVersion
    jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'  # Path to your JDK 17
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
