trigger:
- main

pool:
  name: fasil-pool
  demands:
    - Agent.Name -equals shanu

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      whoami